apiVersion: v1
kind: Pod
metadata:
  name: pod-1-podaffinity
  labels:
    role: frontend
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP