apiVersion: v1
kind: Pod
metadata:
  name: pod-nap
spec:
  containers:
  - name: web
    image: nginx
    ports:
      - name: web
        containerPort: 80
        protocol: TCP
    resources:
      limits:
        cpu: "2"
      requests:
        cpu: "2"