apiVersion: v1
kind: Pod
metadata:
  name: multi-no-valid-nodeselector
  labels:
    role: foo
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
  nodeSelector:
    cloud.google.com/gke-nodepool: default-pool
    topology.gke.io/zone: us-central1-b