apiVersion: v1
kind: Pod
metadata:
  name: pod-valid-nodeselector-toleration
  labels:
    role: foo
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
  tolerations:
    - key: team
      operator: Equal
      value: seven
      effect: "NoSchedule"
  nodeSelector:
    cloud.google.com/gke-nodepool: pool-3